# hacma/config.yaml
name: HACMA - HA-Add-on Fabrikator
version: 1.0.0
slug: hacma
description: Dynamically generates new HA add-ons based on a Docker Compose YAML definition.
url: 'https://github.com/johnbubak/hacma'
startup: once
boot: manual
arch:
  - amd64
  - aarch64
host_network: true
map:
  - homeassistant_config:rw
options:
  # Standard-Werte f체r alle Felder, um die Sichtbarkeit im UI zu gew채hrleisten
  project_name_selector: none
  compose_yaml: []               
  port_mappings: []              
  env_vars: []                   
  command_override: ""           
  device_mappings: []            
  action: none
schema:
  # --- 1. PROJEKT-MANAGER ---
  project_name_selector: 'match(^none$)'
  
  # --- 2. HAUPT-EINGABE (TEXTAREA) ---
  compose_yaml: 'list(str)'
  
  # --- 3. SPEZIFISCHE OVERRIDES (STRUKTURIERT & TYP-VERWENDUNG) ---
  
  # Port-Mapping: Strukturiert, host und container verwenden den HA-Typ 'port'
  port_mappings:
    - host: port?
      container: port?
  
  # Umgebungsvariablen (Bleibt als list(str) f체r einfache Textarea)
  env_vars: 'list(str)?'
  
  # Command Override
  command_override: 'str?'
  
  # Ger채te-Mappings: Verwendet den spezifischen 'device'-Typ
  device_mappings: 'list(device)?'
  
  # --- 4. AKTION ---
  action: 'match(^none$|^load_config$|^generate_and_up$|^down_and_remove$)'