# hacma/config.yaml
name: HACMA - HA-Add-on Fabrikator
version: 2.1.0 
slug: hacma
description: Dynamically generates new HA add-ons based on a Docker Compose YAML definition fetched from a URL. Includes GitHub publishing feature.
url: 'https://github.com/johnbubak/hacma'
startup: once
boot: manual
arch:
  - amd64
  - aarch64
host_network: true
map:
  - homeassistant_config:rw

options:
  # Management
  project_name_selector: none
  compose_url: ""             
  action: none
  
  # NEUE GITHUB FELDER
  publish_addon: false               
  github_pat: ""                     

  # Service Overrides
  image: ""
  container_name: ""
  restart: "unless-stopped"      
  command: ""
  ports: ""
  environment: ""
  volumes: ""
  devices: ""
  networks: ""
  
  # Top-Level Definitionen
  top_level_volumes: ""
  top_level_networks: ""

schema:
  # --- 1. PROJEKT-MANAGER (Laden/Löschen) ---
  project_name_selector: 'match(^none$)'
  
  # --- 2. HAUPT-EINGABE ---
  compose_url: 'str'
  
  # --- 3. GITHUB VERÖFFENTLICHUNG ---
  publish_addon: 'bool'         
  github_pat: 'str?'           
  
  # --- 4. SPEZIFISCHE SERVICE OVERRIDES ---
  image: 'str?'
  container_name: 'str?'
  restart: 'str?'
  command: 'str?'   
  ports: 'str?'     
  environment: 'str?'
  volumes: 'str?'   
  devices: 'str?'   
  networks: 'str?'  
  
  # --- 5. TOP-LEVEL DEFINITIONEN ---
  top_level_volumes: 'str?'
  top_level_networks: 'str?'
  
  # --- 6. AKTION ---
  action: 'match(^none$|^load_config$|^generate_and_up$|^down_and_remove$)'