# hacma/config.yaml (im Ordner hacma/)
name: HACMA - HA-Add-on Fabrikator
version: 0.0.1
slug: hacma
description: Dynamically generates new HA add-ons based on a Docker Compose YAML definition.
url: 'https://github.com/johnbubak/hacma'
startup: once
boot: manual
arch:
  - amd64
  - aarch64
host_network: true
map:
  - homeassistant_config:rw
options:
  project_name_selector: none
  compose_yaml: []               # Initialwert muss zu 'list' passen
  port_mappings: []
  env_vars: []                   # Initialwert muss zu 'list' passen
  command_override: ""
  device_mappings: []
  action: none
schema:
  # --- 1. PROJEKT-MANAGER ---
  project_name_selector: 'match(^none$)'
  
  # --- 2. HAUPT-EINGABE (WIRD ZUR TEXTAREA DURCH LIST) ---
  # ÄNDERUNG: 'list(str)' erzwingt eine Textarea.
  # DAS SKRIPT MUSS DIESEN LIST-TYP BEHANDELN!
  compose_yaml: 'list(str)'
  
  # --- 3. SPEZIFISCHE OVERRIDES ---
  # 'list(str)?' sollte bereits eine Textarea rendern
  port_mappings: 'list(str)?'
  
  # ÄNDERUNG: Auch ENV_VARS auf LIST umgestellt, um sicher Textarea zu bekommen
  env_vars: 'list(str)?'
  
  # Command Override: Bleibt 'str?' (einzeilig), da es meist ein einzelner Befehl ist.
  # Wenn Sie auch hier eine Textarea wollen: auf 'list(str)?' umstellen.
  command_override: 'str?'
  
  device_mappings: 'list(str)?'
  
  # --- 4. AKTION ---
  action: 'match(^none$|^load_config$|^generate_and_up$|^down_and_remove$)'