# hacma/config.yaml
name: HACMA - HA-Add-on Fabrikator
version: 0.2.2
slug: hacma
description: Dynamically generates new HA add-ons based on a Docker Compose YAML definition fetched from a URL. Includes GitHub publishing feature.
url: 'https://github.com/johnbubak/hacma'
startup: once
boot: manual
arch:
  - amd64
  - aarch64
host_network: true
map:
  - homeassistant_config:rw

options:
  # Management
  project_name_selector: none
  # Voreingestellte URL für ein minimales WordPress-Compose-File (ersetzen Sie diese)
  compose_url: "https://raw.githubusercontent.com/Ihre-Quelle/HACMA-Templates/main/wordpress-minimal.yml" 
  action: none
  
  # NEUE GITHUB FELDER
  publish_addon: false               
  github_pat: ""                     

  # --- SERVICE OVERRIDES (WordPress Defaults) ---
  image: "wordpress:latest"
  container_name: "addon_wp_web"
  restart: "always"      
  
  # Standard-Listen-Werte (als YAML-Listen dargestellt)
  command: [] # Standardmäßig leer
  
  # Ports (Host:Container)
  ports: 
    - "80"
    
  # Environment (KEY=VALUE-Format)
  environment: 
    - "WORDPRESS_DB_HOST=db:3306"
    - "WORDPRESS_DB_NAME=wordpress_db"
    - "WORDPRESS_DB_USER=wp_user"
    - "WORDPRESS_DB_PASSWORD=your_strong_password"
    
  # Volumes (Host:Container)
  volumes: 
    - "/data/plugins:/var/www/html/wp-content/plugins"
    - "/data/themes:/var/www/html/wp-content/themes"
    - "/data/uploads:/var/www/html/wp-content/uploads"
    - "/data/wp_core:/var/www/html"
    
  devices: []
  networks: []
  
  # Top-Level Definitionen
  top_level_volumes: []
  top_level_networks: []

schema:
  # --- 1. PROJEKT-MANAGER ---
  project_name_selector: 'match(^none$)'
  
  # --- 2. HAUPT-EINGABE ---
  compose_url: 'str'
  
  # --- 3. GITHUB VERÖFFENTLICHUNG ---
  publish_addon: 'bool'         
  github_pat: 'str?'           
  
  # --- 4. SPEZIFISCHE SERVICE OVERRIDES (Wichtige Schema-Änderungen) ---
  image: 'str?'
  container_name: 'str?'
  restart: 'str?'
  command: 'list(str)?'
  ports: 'list(str)?'     
  environment: 'list(str)?'
  volumes: 'list(str)?'   
  devices: 'list(str)?'   
  networks: 'list(str)?'  
  
  # --- 5. TOP-LEVEL DEFINITIONEN (Wichtige Schema-Änderungen) ---
  top_level_volumes: 'list(str)?'
  top_level_networks: 'list(str)?'
  
  # --- 6. AKTION ---
  action: 'match(^none$|^load_config$|^generate_and_up$|^down_and_remove$)'